### ISSUE TITLE
Build broken on 1.15

### ISSUE THREAD

**Issue by dbrgn** [hyperium/mime.rs#49]
The commit bbc9f80d broke the build on Rust 1.15:

```rust
$ rustup run 1.15.0 cargo build
   Compiling mime v0.2.5 (file:///mnt/data/Projects/mime.rs)
error[E0001]: unreachable pattern
   --> src/lib.rs:165:21
    |
165 |                       _ => false
    |                       ^ this is an unreachable pattern
...
294 |   enoom! {
    |  _- starting here...
295 | |     pub enum Value;
296 | |     Ext;
297 | |     Utf8, "utf-8";
298 | | }
    | |_- ...ending here: in this macro invocation

error: aborting due to previous error

error: Could not compile `mime`.

To learn more, run the command again with --verbose.
```

Is that acceptable? If yes, could you state the minimal supported Rust version in the README and add 1.15 as a target to Travis?

**Comment by seanmonstar** [comment]
Nope, that's a mistake. It was a lint that I could allow on Rust 1.19, I just assumed that it was always that way. I've published 0.2.6 that no longer triggers this error. Sorry about that!

**Comment by dbrgn** [comment]
Thanks :) Maybe adding both `stable` and the minimal supported Rust version to the Travis config might help?

**Comment by seanmonstar** [comment]
Most likely. Finding the minimum Rust version takes time :)

**Comment by dbrgn** [comment]
I usually choose 1.15 since that's the first version with `?` support (iirc) :)
